version: '2'

services:
    carotte:
        build:
            context: .  
        restart: always
        ports: 
            - 8000:8000
        depends_on:
            - carottedb
        links:
            - carottedb
        container_name: carotte_tardis

    carottedb:
        image: mariadb
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: toor
        container_name: carotte_tardis_db
    